# ==============================
# CONFIGURACION GENERAL PROYECTO
# ==============================

project:
  name: prediccion_demanda_supermercado
  version: 1.0

  authors:
    - Juan Camilo Rodriguez
    - William Olaya
    - Erik Gonzales
    - Juan Manuel Garzon
    - Yeimer Macana
          

# ==============================
# RUTAS DE DATOS
# ==============================

paths:
  raw_data: data/raw/dataset_supermercado_colombia_50000.csv
  processed_data: data/processed/ventas_limpias.csv
  features_data: data/features/dataset_modelo.csv

# ==============================
# MODELO DE MACHINE LEARNING
# ==============================

model:
  algorithm: xgboost
  test_size: 0.2
  random_state: 42

# ==============================
# CONFIGURACION DE KPIs
# ==============================

kpis:
  inventory_rotation: true
  expired_losses: true
  promotion_impact: true
  goals:
    rotation_min: 0.8
    expired_loss_max: 0.05
    promotion_increase_min: 0.15

# ==============================
# DATA WAREHOUSE
# ==============================

warehouse:
  db_path: data/warehouse/data_warehouse.db

# ==============================
# REPORTES
# ==============================

reports:
  save_figures: true
  figures_path: reports/figures/
  reports_path: reports/generated/
  natural_report_path: reports/generated/reporte_natural.txt
  kpis_csv: reports/generated/kpis_estado.csv
  predictions_csv: reports/generated/predicciones_futuras.csv

# ==============================
# DASHBOARD
# ==============================

dashboard:
  enable: true
  port: 8501