@echo off
REM Ejecuta pipeline completo y dashboard
cd /d "%~dp0"
echo 1) Instalar dependencias...
pip install -r requirements.txt
echo 2) Generar dataset (60k)...
python scripts/generate_dataset.py
echo 3) Ejecutar pipeline completo...
python main.py
echo 4) Iniciar dashboard (Streamlit)...
start "" streamlit run dashboard/app.py
echo Listo: abre http://localhost:8501